import Header from "../components/Header";
import LateralMenu from "../components/LateralMenu";
import StyledJsxRegistry from "./registry";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body style={{ margin: 0 }}>
        <StyledJsxRegistry>
          <Header />
          <LateralMenu />
          {children}
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
