import Header from "../components/Header";
import LateralMenu from "../components/LateralMenu";
import StyledJsxRegistry from "./registry";
import '../styles/global.css';
import { roboto } from '../utils/fonts';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
        <StyledJsxRegistry>
          <Header />
          <main>
            <LateralMenu />
            {children}
          </main>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
